language: go
sudo: false
go:
- 1.x
- 1.11.x
- 1.12.x
- 1.13.x
install:
- go get github.com/Masterminds/glide
- go get github.com/go-playground/overalls
- go get github.com/mattn/goveralls
- go get github.com/alecthomas/gometalinter
- gometalinter --install
script:
- glide install
- gometalinter --vendor --config=gometalinter.json ./...
- overalls -project=github.com/mmcloughlin/random -covermode=atomic -- -race -v
- goveralls -coverprofile=overalls.coverprofile -service=travis-ci
