language: go
sudo: false
go:
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - tip
install:
  - go get github.com/Masterminds/glide
  - go get github.com/go-playground/overalls
  - go get github.com/mattn/goveralls
  - go get github.com/alecthomas/gometalinter
  - gometalinter --install
script:
  - glide install
  - gometalinter --vendor --config=gometalinter.json ./...
  - overalls -project=github.com/mmcloughlin/random -covermode=atomic -- -race -v
  - goveralls -coverprofile=overalls.coverprofile -service=travis-ci
