package random

import mock "github.com/stretchr/testify/mock"

// MockSeeder is an autogenerated mock type for the Seeder type
type MockSeeder struct {
	mock.Mock
}

// Seed provides a mock function with given fields:
func (_m *MockSeeder) Seed() (int64, error) {
	ret := _m.Called()

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
